-- jayla jones (INSERT - UPDATE - DELETE)

-- ADD A NEW SUPPLIER
INSERT INTO 
suppliers
VALUES
('DOLL HOUSE GROCERIES', 'JAYLA JONES', 'CEO', '333 DOLL AVENUE', 'NEW YORK', 'NY', '11201','USA','212-333-2233');

-- ADD A NEW PRODUCT PROVIDED BY NEW SUPPLIER
INSERT INTO
products
VALUES
('CAVIAR', 
